<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Unibiz Gutenverse Home Hero', 'unibiz' ),
	'categories' => array( 'unibiz-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1260","Tablet":""},"gap":"no","elementId":"guten-uwexGI","overflow":"hidden","background":{"type":"gradient","image":{"Desktop":[]},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"color":{"type":"variable","id":"gv-color-background-primary"},"yposition":{"Desktop":{"unit":"%","point":"66"}},"xposition":{"Desktop":{"unit":"%","point":"50"}},"gradientColor":[{"color":"rgba(169, 105, 230, 1)","active":false,"opacity":1,"id":1,"offset":"0.035"},{"color":"rgba(66, 35, 142, 1)","active":true,"opacity":1,"id":5,"offset":"0.375"},{"color":"rgba(29, 22, 86, 1)","active":false,"opacity":1,"id":4,"offset":"0.620"},{"color":"rgba(17, 21, 64, 1)","active":false,"opacity":1,"id":2,"offset":"0.895"}],"gradientType":"radial","gradientRadial":"bottom center"},"backgroundOverlay":{"type":"default","image":{"Desktop":{"id":3110,"image":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/bg-overlay-circle.png"}},"position":{"Desktop":"center center"},"size":{"Desktop":"default"}},"opacity":"1","padding":{"Desktop":{"unit":"px","dimension":{"top":"160","right":"0","bottom":"0","left":"0"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"120","right":"20","bottom":"0","left":"20"}}}} -->
<div class="section-wrapper" data-id="uwexGI"><section class="wp-block-gutenverse-section guten-element guten-section guten-uwexGI layout-boxed align-stretch overflow-hidden"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-qnWHGz","horizontalAlign":{"Desktop":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-qnWHGz"><div class="guten-column-wrapper" data-id="qnWHGz"><!-- wp:gutenverse/wrapper {"elementId":"guten-WkvYaa","displayType":"flex","displayWidth":{"Desktop":{"unit":"px","point":"800"}},"displayHeight":{"Desktop":{"unit":"px"}},"horizontalAlign":{"Desktop":"center","Tablet":false,"Mobile":false},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"40"}},"Mobile":{"unit":"px","dimension":{"bottom":"30"}}}} -->
<div class="guten-element guten-wrap-helper no-margin guten-WkvYaa flex"><div class="guten-inner-wrap" data-id="WkvYaa"><!-- wp:gutenverse/heading {"elementId":"guten-6hoJoU","type":1,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-primary","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"64"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.125"}},"weight":"700","spacing":{"Desktop":"-0.02"}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"24","left":"0"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"775"}}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-6hoJoU">Experience The New 100% Multipurpose FSE Theme</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-coatvZ","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text-hero","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.6"}}},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"80","bottom":"32","left":"80"}},"Tablet":{"unit":"px","dimension":{"right":"60","left":"60"}},"Mobile":{"unit":"px","dimension":{"right":"0","left":"0","bottom":"24"}}},"positioningType":{"Desktop":"default"},"positioningWidth":{"Desktop":{"unit":"px","point":"360"}}} -->
<div class="guten-element gutenverse-text-editor guten-coatvZ"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Build any website you want for business, portfolio, blogging, or freelancer, faster and lighter using just one theme without ever switching again.</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-ddSaHa","content":"Get Started Now","alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"24","bottom":"17","left":"24"}},"Mobile":{"unit":"px","dimension":{"right":"20","left":"20","top":"13","bottom":"15"}}},"buttonBackground":{"type":"gradient","gradientColor":[{"color":"rgba(159, 101, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(72, 57, 240, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"9","right":"9","bottom":"9","left":"9"}}}},"background":{"type":"gradient","color":{"type":"variable","id":"custom-text-primary"},"gradientColor":[{"color":"rgba(207, 178, 255, 1)","active":false,"opacity":1,"id":1,"offset":"0.000"},{"color":"rgba(73, 58, 241, 1)","active":true,"opacity":1,"id":2,"offset":"1.000"}]},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","right":"10","bottom":"10","left":"10"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"1","right":"1","bottom":"1","left":"1"}}},"color":{"type":"variable","id":"gv-color-dark-text-primary"},"typography":{"type":"variable","id":"gv-font-button-primary","size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.5"}},"weight":"600","font":{"label":"Host Grotesk","value":"Host Grotesk","type":"google"}},"hoverTextColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"positioningType":{"Desktop":"inline"}} -->
<div class="guten-element guten-button-wrapper guten-ddSaHa"><a class="guten-button guten-button-sm" href="#"><span>Get Started Now</span></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/wrapper -->

<!-- wp:gutenverse/image {"elementId":"guten-Tg3GAI","imgSrc":{"media":{"imageId":3109,"sizes":{"thumbnail":{"height":150,"width":150,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mockup-demo.webp","orientation":"landscape"},"medium":{"height":128,"width":300,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mockup-demo.webp","orientation":"landscape"},"large":{"height":437,"width":1024,"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mockup-demo.webp","orientation":"landscape"},"full":{"url":"' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mockup-demo.webp","height":669,"width":1568,"orientation":"landscape"}}},"size":"full"},"altOriginal":"","captionOriginal":"","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"0","right":"-24","left":"-24"}},"Tablet":{"unit":"px","dimension":{"right":"0","left":"0"}}},"positioningType":{"Desktop":"custom"},"positioningWidth":{"Desktop":{"unit":"%","point":"130"}}} -->
<div class="wp-block-gutenverse-image guten-element guten-image guten-Tg3GAI"><div class="guten-image-wrapper"><img class="gutenverse-image-box-filled" src="' . esc_url( trailingslashit( get_template_directory_uri() ) ) . 'assets/img/mockup-demo.webp" height="669" width="1568"/></div></div>
<!-- /wp:gutenverse/image --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'is_sync' => false,
);
