<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Home Feature', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-Rthj1H","background":{"type":"default","color":{"r":255,"g":255,"b":255,"a":1},"videoPlayOnMobile":false},"margin":{"Tablet":[],"Desktop":[]},"padding":{"Tablet":{"unit":"px","dimension":{"left":"10","right":"10"}},"Desktop":[]}} -->
<div class="section-wrapper" data-id="Rthj1H"><section class="wp-block-gutenverse-section guten-element guten-section guten-Rthj1H layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-XTtDqn"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-XTtDqn"><div class="guten-column-wrapper" data-id="XTtDqn"><!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"isChild":true,"gap":"no","elementId":"guten-gnUI0k","margin":{"Desktop":{"unit":"px","dimension":{"top":"-120"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="gnUI0k"><section class="wp-block-gutenverse-section guten-element guten-section guten-gnUI0k layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-w4RFxJ","border":{"radius":{"Desktop":[]}},"margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-w4RFxJ animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="w4RFxJ"><!-- wp:gutenverse/icon-box {"elementId":"guten-tNYwfa","title":"Best Service","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-laptop-code","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"parentSelector":".guten-tNYwfa:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-tNYwfa guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="fas fa-laptop-code icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Best Service</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor</p><!-- wp:gutenverse/button {"elementId":"guten-pRMJOZ","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"gv-color-accent"},"hoverIconColor":{"type":"variable","id":"gv-color-text-primary"},"parentSelector":".guten-tNYwfa:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-pRMJOZ"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg fas fa-arrow-alt-circle-right"></i><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-PqwXja","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-PqwXja animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="PqwXja"><!-- wp:gutenverse/icon-box {"elementId":"guten-Z3I65A","title":"Affordable Price","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-money-check-alt","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[],"Tablet":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"parentSelector":".guten-Z3I65A:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-Z3I65A guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="fas fa-money-check-alt icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Affordable Price</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor</p><!-- wp:gutenverse/button {"elementId":"guten-WtVhJW","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"gv-color-accent"},"hoverIconColor":{"type":"variable","id":"gv-color-accent-hover"},"parentSelector":".guten-Z3I65A:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-WtVhJW"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg fas fa-arrow-alt-circle-right"></i><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":23,"Tablet":50},"elementId":"guten-Zr3b6B","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"0","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Zr3b6B animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="Zr3b6B"><!-- wp:gutenverse/icon-box {"elementId":"guten-WuZ7nE","title":"24/7 Support","titleTag":"h3","description":"Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor","icon":"fas fa-user-check","iconSize":{"Desktop":"40"},"iconPosition":"top","containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"35","right":"30","bottom":"35","left":"30"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":[]},"containerPaddingHover":{"Desktop":[]},"containerBackground":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"containerBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":[],"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"all":{"type":"none"},"bottom":{"type":"none","color":{"r":43,"g":123,"b":123,"a":1},"width":"8"}},"containerBoxShadow":{"horizontal":"0","vertical":"3","blur":"15","spread":"0","color":{"r":16,"g":16,"b":16,"a":0.1}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"15","left":""}}},"iconColor":{"type":"variable","id":"gv-color-accent"},"iconBgColor":{"r":254,"g":254,"b":254,"a":0},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"titleMargin":{"Desktop":[],"Mobile":[]},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":[]},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"parentSelector":".guten-WuZ7nE:hover .guten-icon-box-wrapper","hasInnerBlocks":true} -->
<div class="guten-element guten-WuZ7nE guten-icon-box icon-position-top"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="fas fa-user-check icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">24/7 Support</h3><p class="icon-box-description">Lorem ipsum dolor sit amet, consectet adipiscing elit, sed do eiusmod tempor dolor</p><!-- wp:gutenverse/button {"elementId":"guten-ZHkkfd","url":"#","buttonWidth":{"Desktop":""},"alignButton":{"Desktop":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Tablet":[]},"buttonBackground":{"type":"default","color":{"r":217,"g":217,"b":217,"a":0}},"showIcon":true,"icon":"fas fa-arrow-alt-circle-right","iconSize":{"Desktop":{"point":"26","unit":"px"}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"iconColor":{"type":"variable","id":"gv-color-accent"},"hoverIconColor":{"type":"variable","id":"gv-color-accent-hover"},"parentSelector":".guten-WuZ7nE:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-button-wrapper guten-ZHkkfd"><a class="guten-button guten-button-sm" href="#"><i class="fa-lg fas fa-arrow-alt-circle-right"></i><span></span></a></div>
<!-- /wp:gutenverse/button --></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":31,"Tablet":50,"Mobile":null},"elementId":"guten-uGayZj","background":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"30","bottom":"30"}},"Tablet":{"unit":"px","dimension":{"top":"0","bottom":"30"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"40","right":"40","bottom":"40","left":"40"}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}},"Tablet":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"25","left":"30"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-uGayZj animated guten-element-hide desktop-fadeInRight"><div class="guten-column-wrapper" data-id="uGayZj"><!-- wp:gutenverse/heading {"elementId":"guten-d04zkC","type":3,"textAlign":{"Mobile":"center"},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-feature-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"22"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"border":{"radius":{"Tablet":[]}},"margin":{"Tablet":[]},"padding":{"Tablet":[]}} -->
<h3 class="wp-block-gutenverse-heading guten-element guten-d04zkC">Make Appointment</h3>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-2OYpNl","alignment":{"Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false} -->
<div class="guten-element gutenverse-text-editor guten-2OYpNl"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incidid </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/button {"elementId":"guten-RVDyDU","content":"Get Started","alignButton":{"Mobile":"center"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Mobile":[]},"buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}}},"buttonBorderHover":{"radius":{"Desktop":[]}},"showIcon":true,"icon":"fas fa-arrow-right","iconPosition":"after","iconSpacing":{"Desktop":"8"},"iconSize":{"Desktop":{"point":"13","unit":"px"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"color":{"type":"variable","id":"gv-color-primary"},"iconColor":{"type":"variable","id":"gv-color-primary"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverTextColor":{"type":"variable","id":"gv-color-white"}} -->
<div class="guten-element guten-button-wrapper guten-RVDyDU"><a class="guten-button guten-button-sm" href="#"><span>Get Started</span><i class="fa-lg fas fa-arrow-right"></i></a></div>
<!-- /wp:gutenverse/button --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'pattern_slug' => 'startupzy-companion/startupzy-gutenverse-home-feature',
	'is_sync' => false,
);
