<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse 404 Hero', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"elementId":"guten-pNrAbp","background":{"type":"default","image":{"Desktop":{"id":4,"image":"{{{image:0:url}}}"}},"position":{"Desktop":"center center"},"repeat":{"Desktop":"no-repeat"},"size":{"Desktop":"cover"},"videoPlayOnMobile":false},"backgroundOverlay":{"type":"default","color":{"type":"variable","id":"gv-color-background-primary"}},"opacity":"0.9","margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-70"}},"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"300","bottom":"300"}},"Tablet":{"unit":"px","dimension":{"top":"160","bottom":"140"}},"Mobile":{"unit":"px","dimension":{"top":"120","bottom":"120","right":"10","left":"10"}}}} -->
<div class="section-wrapper" data-id="pNrAbp"><section class="wp-block-gutenverse-section guten-element guten-section guten-pNrAbp layout-boxed align-stretch"><div class="guten-background-overlay"></div><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100,"Tablet":null,"Mobile":null},"elementId":"guten-2ZmwgH","horizontalAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-2ZmwgH"><div class="guten-column-wrapper" data-id="2ZmwgH"><!-- wp:gutenverse/heading {"elementId":"guten-GuptEo","type":1,"textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-heading-404","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"160"},"Mobile":{"unit":"px","point":"84"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"-30","top":"","right":"","left":""}},"Mobile":{"unit":"px","dimension":{"bottom":"-15"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<h1 class="wp-block-gutenverse-heading guten-element guten-GuptEo">404</h1>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-jV5c6f","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"white"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":{"unit":"px","dimension":{"bottom":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-jV5c6f">Page Not Found</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-WKSHFw","alignment":{"Desktop":"center"},"textColor":{"type":"variable","id":"gv-color-dark-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"20"}},"Mobile":[]},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element gutenverse-text-editor guten-WKSHFw"><div class="text-content-inner"><!-- wp:paragraph -->
<p>It looks like nothing was found at this location. Maybe try a search?</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/search {"elementId":"guten-v45ujz","formStyle":{"Desktop":"fit-content","Mobile":"100%"},"buttonWidth":{"Desktop":{"point":"100","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"margin":{"Desktop":{"unit":"px","dimension":{"bottom":"60","top":"10"}},"Mobile":{"unit":"px","dimension":{"bottom":"0","top":"10"}}},"padding":{"Desktop":[],"Mobile":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputPlaceholder":"Search here...","inputPadding":{"Desktop":{"unit":"px","dimension":{"left":"20","right":"20"}},"Tablet":[],"Mobile":[]},"inputMargin":{"Desktop":{"unit":"px","dimension":{"right":"16"}},"Tablet":[],"Mobile":{"unit":"px","dimension":{"right":"4"}}},"inputHeight":{"Desktop":"56","Mobile":"48"},"inputWidth":{"Desktop":{"unit":"%","point":"60"},"Tablet":{"unit":"%","point":"80"},"Mobile":{"unit":"%","point":"100"}},"inputTypography":{"type":"variable","id":"gv-font-text-small","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-primary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10"}}},"all":{"type":"none","width":null,"color":""}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputBorderHoverResponsive":{"Tablet":{"radius":[]},"Mobile":{"radius":[]}},"inputBgColorNormal":{"Desktop":{"type":"variable","id":"gv-color-white"}},"alignContent":{"Desktop":"center","Tablet":"center","Mobile":"center"}} -->
<div class="guten-element guten-v45ujz guten-search"><form class="gutenverse-search-form"><div class="search-input-container-outer"><div class="search-input-container"><input type="text" placeholder="Search here..." name="s" class="gutenverse-search gutenverse-search-input"/><div class="close-icon"><i class="gtn gtn-x-line"></i></div></div></div><div class="guten-search-button-wrapper"><!-- wp:gutenverse/button {"elementId":"guten-2SjYB4","role":"submit","content":"Search","buttonSize":"xs","buttonWidth":{"Mobile":"100"},"paddingButton":{"Desktop":[],"Mobile":[]},"buttonBackground":{"color":{"type":"variable","id":"gv-color-accent"},"type":"default"},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"white"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"10","bottom":"10"}}}},"margin":{"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Mobile":[]},"color":{"type":"variable","id":"gv-color-white"},"iconColor":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"hoverIconColor":{"type":"variable","id":"gv-color-accent"},"hoverTextColor":{"type":"variable","id":"gv-color-accent"}} -->
<div class="guten-element guten-button-wrapper guten-2SjYB4"><button class="guten-button guten-button-xs" type="submit"><span>Search</span></button></div>
<!-- /wp:gutenverse/button --></div></form></div>
<!-- /wp:gutenverse/search --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '["https:\/\/gutenverse.com\/startupzy\/wp-content\/uploads\/sites\/4\/2025\/09\/action-african-american-african-descent-agreement-american-black-1448357-pxhere.com_.webp"]',
	'pattern_slug' => 'startupzy-companion/startupzy-gutenverse-404-hero',
	'is_sync' => false,
);
