<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Gutenverse Team', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-N51LwF","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"120"}},"Tablet":{"unit":"px","dimension":{"top":"80","bottom":"80","right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","bottom":"20"}}}} -->
<div class="section-wrapper" data-id="N51LwF"><section class="wp-block-gutenverse-section guten-element guten-section guten-N51LwF layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":100},"elementId":"guten-9407cx","margin":{"Desktop":[]},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-9407cx"><div class="guten-column-wrapper" data-id="9407cx"><!-- wp:gutenverse/heading {"elementId":"guten-3tPrxG","type":5,"textAlign":{"Desktop":"center"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-subheading","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-3tPrxG animated guten-element-hide desktop-fadeInUp">Our Team</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-TzgyWw","textAlign":{"Desktop":"center","Tablet":"center","Mobile":"center"},"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-TzgyWw animated guten-element-hide desktop-fadeInUp">Meet With Professional Team</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-F4Bdav","alignment":{"Desktop":"center","Tablet":"center","Mobile":"center"},"textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"%","dimension":{"right":"27","left":"27"}},"Tablet":{"unit":"%","dimension":{"right":"12","left":"12"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-F4Bdav animated guten-element-hide desktop-fadeInUp"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua</p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-NVGsj6","margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20"}},"Tablet":[]},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"none"},"duration":"normal"}} -->
<div class="section-wrapper" data-id="NVGsj6"><section class="wp-block-gutenverse-section guten-element guten-section guten-NVGsj6 layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-TBZHjG","margin":{"Desktop":{"unit":"px","dimension":{"right":"20"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"200"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-TBZHjG animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="TBZHjG"><!-- wp:gutenverse/team {"elementId":"guten-9Ut7wr","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","src":{"id":42,"image":"{{{image:0:url}}}"},"name":"Jennifer Doe","job":"Marketing","nameColor":{"type":"variable","id":"gv-color-white"},"nameTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"jobColor":{"type":"variable","id":"gv-color-white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"descColor":{"type":"variable","id":"white"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBackgroundHover":{"type":"default","color":""},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"type":"default","id":"startupzy-team-overlay","color":{"r":3,"g":21,"b":48,"a":0.9}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-9Ut7wr"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="{{{image:0:url}}}" alt="Jennifer Doe"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Jennifer Doe</h3><p class="profile-sub" aria-label="Profile Job">Marketing</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-FSnYGV","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"gv-color-accent"},"hoverBgColor":{"type":"variable","id":"gv-color-white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-FSnYGV circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-ihuapy"} -->
<div class="guten-element guten-social-icon guten-ihuapy facebook"><a id="guten-ihuapy" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-3CDTMm"} -->
<div class="guten-element guten-social-icon guten-3CDTMm twitter"><a id="guten-3CDTMm" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-fkuBJf"} -->
<div class="guten-element guten-social-icon guten-fkuBJf instagram"><a id="guten-fkuBJf" href="#"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-EJID1Y","margin":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"20","right":"","bottom":"","left":""}}},"padding":{"Desktop":{"unit":"px","dimension":{"right":"10","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-EJID1Y animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="EJID1Y"><!-- wp:gutenverse/team {"elementId":"guten-MyOrrl","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","overlayProfilePosition":{"Desktop":{"point":"","unit":"px"}},"src":{"id":43,"image":"{{{image:1:url}}}"},"name":"Jonathan Doe","job":"CEO Startupzy","nameColor":{"type":"variable","id":"gv-color-white"},"nameTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"jobColor":{"type":"variable","id":"gv-color-white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"descColor":{"type":"variable","id":"white"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBackgroundHover":{"type":"default","color":""},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"type":"default","id":"startupzy-team-overlay","color":{"r":3,"g":21,"b":48,"a":0.9}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-MyOrrl"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="{{{image:1:url}}}" alt="Jonathan Doe"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Jonathan Doe</h3><p class="profile-sub" aria-label="Profile Job">CEO Startupzy</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-9jB2dJ","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"gv-color-accent"},"hoverBgColor":{"type":"variable","id":"gv-color-white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-9jB2dJ circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-bVafkf","iconSize":{"Desktop":{"unit":"px"}}} -->
<div class="guten-element guten-social-icon guten-bVafkf facebook"><a id="guten-bVafkf" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-s35QKL"} -->
<div class="guten-element guten-social-icon guten-s35QKL twitter"><a id="guten-s35QKL" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-5cVNAI"} -->
<div class="guten-element guten-social-icon guten-5cVNAI instagram"><a id="guten-5cVNAI" href="#"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":33.33,"Mobile":null},"elementId":"guten-xHFRTu","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"animation":{"type":{"Desktop":"fadeInUp"},"duration":"normal","delay":"600"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-xHFRTu animated guten-element-hide desktop-fadeInUp"><div class="guten-column-wrapper" data-id="xHFRTu"><!-- wp:gutenverse/team {"elementId":"guten-PWwyAs","profileType":"overlay","overlayType":"scale","overlayPosition":"bottom","src":{"id":44,"image":"{{{image:2:url}}}"},"name":"Christina Doe","job":"Creative Leader","nameColor":{"type":"variable","id":"gv-color-white"},"nameTypography":{"type":"variable","id":"gv-font-feature","font":{"label":"Helvetica","value":"Helvetica","type":"google"},"size":{"Desktop":{"unit":"px","point":"24"},"Mobile":{"unit":"px","point":"20"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.2"}},"weight":"600"},"jobColor":{"type":"variable","id":"gv-color-white"},"jobTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"descColor":{"type":"variable","id":"white"},"descTypography":{"font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"point":"16","unit":"px"}},"weight":"400"},"profilePadding":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Tablet":[],"Mobile":[]},"detailsPadding":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"","bottom":"30","left":""}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"30","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40"}}},"profileBorderRadius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}},"Tablet":[],"Mobile":[]},"profileBorder":{"radius":{"Desktop":[]}},"imageBackgroundHover":{"type":"default","color":""},"imageBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"imgWidth":{"Tablet":{"point":"240","unit":"px"},"Mobile":{"unit":"%","point":"100"}},"hoverPadding":{"Desktop":[]},"hoverBgColor":{"type":"default","id":"startupzy-team-overlay","color":{"r":3,"g":21,"b":48,"a":0.9}},"nameSpace":{"Desktop":"6"},"jobSpace":{"Desktop":"34"},"descSpace":{"Desktop":""},"hoverContentBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}}}} -->
<div class="wp-block-gutenverse-team guten-element guten-team guten-PWwyAs"><div class="profile-box"><div class="profile-card card-overlay scale"><img src="{{{image:2:url}}}" alt="Christina Doe"/><div class="profile-body bottom"><h3 class="profile-title " aria-label="Profile Name">Christina Doe</h3><p class="profile-sub" aria-label="Profile Job">Creative Leader</p><div class="socials-wrapper"><!-- wp:gutenverse/social-icons {"elementId":"guten-B5GGdr","iconSize":{"Desktop":{"point":"14","unit":"px"}},"gap":{"Desktop":"10","Tablet":"10","Mobile":"10"},"shape":"circle","color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-accent"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","left":"0","bottom":"5"}}}},"iconBorderHover":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","bottom":"5","right":"0","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"gv-color-accent"},"hoverBgColor":{"type":"variable","id":"gv-color-white"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"-20"}}},"padding":{"Desktop":[]}} -->
<div class="guten-element guten-social-icons guten-B5GGdr circle horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-9I3RjG"} -->
<div class="guten-element guten-social-icon guten-9I3RjG facebook"><a id="guten-9I3RjG" href="#"><i class="gtn gtn-facebook-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-KoGXrf"} -->
<div class="guten-element guten-social-icon guten-KoGXrf twitter"><a id="guten-KoGXrf" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-DVrWAG"} -->
<div class="guten-element guten-social-icon guten-DVrWAG instagram"><a id="guten-DVrWAG" href="#"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div></div></div></div>
<!-- /wp:gutenverse/team --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '["https:\/\/designer.gutenverse.com\/startupzy-companion\/wp-content\/uploads\/sites\/105\/2024\/07\/business-team-executive-group-work-job-1573331-pxhere.com_.webp","https:\/\/designer.gutenverse.com\/startupzy-companion\/wp-content\/uploads\/sites\/105\/2024\/07\/StockSnap_UTEZRDTKPP.webp","https:\/\/designer.gutenverse.com\/startupzy-companion\/wp-content\/uploads\/sites\/105\/2024\/07\/business-team-executive-group-work-job-1573329-pxhere.com_.webp"]',
	'pattern_slug' => 'startupzy-companion/startupzy-gutenverse-team',
	'is_sync' => false,
);
