<?php
/**
 * Pattern content.
 */
return array(
	'title'      => __( 'Startupzy Gutenverse Contact Contact', 'startupzy' ),
	'categories' => array( 'startupzy-gutenverse' ),
	'content'    => '<!-- wp:gutenverse/section {"width":{"Desktop":"1170"},"elementId":"guten-2cw8B7","verticalAlign":"center","margin":{"Desktop":[],"Tablet":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"top":"100","bottom":"100","right":"","left":""}},"Tablet":{"unit":"px","dimension":{"top":"80","right":"10","bottom":"80","left":"10"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"60","left":"0"}}},"zIndex":{"Desktop":"2"},"wrapColumn":{"Desktop":false,"Tablet":true,"Mobile":true}} -->
<div class="section-wrapper" data-id="2cw8B7"><section class="wp-block-gutenverse-section guten-element guten-section guten-2cw8B7 layout-boxed align-stretch"><div class="guten-container guten-column-gap-default"><!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-CWslS9","background":{"type":"default","color":{"type":"variable","id":"gv-color-white"}},"border":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"50","right":"0","bottom":"50","left":"0"}}}},"boxShadow":{"color":{"r":5,"g":5,"b":5,"a":0.08},"horizontal":"0","vertical":"5","blur":"30"},"margin":{"Desktop":{"unit":"px","dimension":{"left":"0","bottom":"0","right":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"","right":"10","bottom":"","left":"10"}}},"padding":{"Desktop":{"unit":"px","dimension":{"top":"60","right":"60","bottom":"60","left":"60"}},"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":{"unit":"px","dimension":{"top":"30","right":"30","bottom":"30","left":"30"}}},"zIndex":{"Desktop":"5"},"animation":{"type":{"Desktop":"fadeInLeft"},"duration":"normal","delay":"400"}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-CWslS9 animated guten-element-hide desktop-fadeInLeft"><div class="guten-column-wrapper" data-id="CWslS9"><!-- wp:gutenverse/form-builder {"elementId":"guten-TZtAs1","formId":{"label":"Contact Form","value":107},"margin":{"Desktop":[]},"padding":{"Desktop":[]},"zIndex":{"Desktop":"2"}} -->
<form style="display:none" class="guten-element guten-form-builder guten-TZtAs1" data-form-id="107"><!-- wp:gutenverse/form-input-text {"elementId":"guten-3bX8Ol","showLabel":false,"inputPlaceholder":"Your Name","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperColor":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"20","bottom":"13","left":"20"}}},"inputMargin":{"Desktop":[]},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}}},"all":{"type":"solid","width":"1","color":{"type":"variable","id":"gv-color-border-input"}}},"inputBorderHover":{"radius":{"Desktop":[]}},"inputColorFocus":{"Desktop":[]},"inputBorderFocus":{"radius":{"Desktop":[]}},"inputBgColorNormal":{"Desktop":[]}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-3bX8Ol hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Name" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-email {"elementId":"guten-oXyIca","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"inputPlaceholder":"Your Email","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"20","bottom":"13","left":"20"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}}},"all":{"type":"solid","color":{"type":"variable","id":"gv-color-border-input"},"width":"1"}},"inputBorderHover":{"radius":{"Desktop":[]}}} -->
<div class="guten-element guten-form-input-email guten-form-input guten-input-position-top guten-oXyIca hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;email&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Email" name="input-email" class="gutenverse-input gutenverse-input-email" type="email"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-email -->

<!-- wp:gutenverse/form-input-text {"elementId":"guten-pK01mc","showLabel":false,"inputPlaceholder":"Your Subject","showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"20","bottom":"13","left":"20"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}}},"all":{"type":"solid","color":{"type":"variable","id":"gv-color-border-input"},"width":"1"}}} -->
<div class="guten-element guten-form-input-text guten-form-input guten-input-position-top guten-pK01mc hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><input data-validation="{&quot;type&quot;:&quot;text&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Subject" name="input-text-name" class="gutenverse-input gutenverse-input-text" type="text"/><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-text -->

<!-- wp:gutenverse/form-input-textarea {"elementId":"guten-aM3jG3","showLabel":false,"showHelper":false,"labelPadding":{"Desktop":[]},"labelMargin":{"Desktop":[]},"helperPadding":{"Desktop":[]},"inputHeight":{"Desktop":"160"},"inputPlaceholder":"Your Message","inputPadding":{"Desktop":{"unit":"px","dimension":{"top":"13","right":"20","bottom":"13","left":"20"}}},"inputMargin":{"Desktop":{"unit":"px","dimension":{"top":"5"}}},"placeholderColor":{"Desktop":{"type":"variable","id":"gv-color-text-placeholder"}},"inputTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"inputColorNormal":{"Desktop":{"type":"variable","id":"gv-color-text-secondary"}},"inputBorderNormal":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}}},"all":{"type":"solid","color":{"type":"variable","id":"gv-color-border-input"},"width":"1"}}} -->
<div class="guten-element guten-form-input-textarea guten-form-input guten-input-position-top guten-aM3jG3 hide-label hide-helper"><div class="label-wrapper"></div><div class="main-wrapper"><textarea data-validation="{&quot;type&quot;:&quot;textarea&quot;,&quot;required&quot;:false,&quot;validationType&quot;:&quot;none&quot;,&quot;validationWarning&quot;:&quot;Input Invalid&quot;}" placeholder="Your Message" name="input-textarea" class="gutenverse-input gutenverse-input-text"></textarea><div class="validation-error">Input Invalid</div></div></div>
<!-- /wp:gutenverse/form-input-textarea -->

<!-- wp:gutenverse/form-input-submit {"elementId":"guten-8fxoMT","content":"Send Message","buttonBackground":{"type":"default","color":{"type":"variable","id":"gv-color-primary"}},"buttonBackgroundHover":{"type":"default","color":{"type":"variable","id":"gv-color-text-primary"}},"buttonBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"20","left":"0"}}}},"margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}}},"padding":{"Desktop":[]},"zIndex":{"Desktop":""},"color":{"type":"variable","id":"gv-color-white"},"typography":{"type":"variable","id":"gv-font-button-primary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"13"}},"lineHeight":{"Desktop":{"unit":"em","point":"1"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"hoverTextColor":{"type":"variable","id":"gv-color-white"},"paddingButton":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"40","bottom":"20","left":"40"}},"Tablet":[]}} -->
<div class="guten-element guten-button-wrapper guten-submit-wrapper guten-8fxoMT"><div class="form-notification"></div><button class="guten-button gutenverse-input-submit guten-button-sm" type="submit"><span>Send Message</span></button><div class="gutenverse-input-submit-loader"><i class="fas fa-spinner fa-spin"></i></div></div>
<!-- /wp:gutenverse/form-input-submit --></form>
<!-- /wp:gutenverse/form-builder --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"sectionVerticalAlign":"center","elementId":"guten-tCwytO","margin":{"Desktop":{"unit":"px","dimension":{"left":"20"}},"Tablet":{"unit":"px","dimension":{"top":"60","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"top":"40","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":{"unit":"px","dimension":{"bottom":"40","top":"40"}},"Tablet":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}},"Mobile":{"unit":"px","dimension":{"right":"10","left":"10"}}}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-tCwytO"><div class="guten-column-wrapper" data-id="tCwytO"><!-- wp:gutenverse/heading {"elementId":"guten-aMPUWb","type":5,"textAlign":{"Desktop":"left","Tablet":"left","Mobile":"left"},"color":{"type":"variable","id":"gv-color-accent"},"typography":{"type":"variable","id":"gv-font-meta","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"spacing":{"Desktop":"0.15"},"transform":"uppercase","weight":"600"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal"}} -->
<h5 class="wp-block-gutenverse-heading guten-element guten-aMPUWb animated guten-element-hide desktop-fadeInRight">Contact Us</h5>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/heading {"elementId":"guten-3kS4kk","color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"gv-font-secondary","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"36"},"Mobile":{"unit":"px","point":"24"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"600"},"containsAnchorTag":false,"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"200"}} -->
<h2 class="wp-block-gutenverse-heading guten-element guten-3kS4kk animated guten-element-hide desktop-fadeInRight">Get In Touch With Us</h2>
<!-- /wp:gutenverse/heading -->

<!-- wp:gutenverse/text-editor {"elementId":"guten-bwmK4G","textColor":{"type":"variable","id":"gv-color-text-secondary"},"typography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"containsAnchorTag":false,"margin":{"Desktop":[],"Mobile":[]},"padding":{"Desktop":{"unit":"px","dimension":{"right":"40"}},"Mobile":{"unit":"px","dimension":{"top":"0","right":"5","bottom":"0","left":"0"}}},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"400"}} -->
<div class="guten-element gutenverse-text-editor guten-bwmK4G animated guten-element-hide desktop-fadeInRight"><div class="text-content-inner"><!-- wp:paragraph -->
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua </p>
<!-- /wp:paragraph --></div></div>
<!-- /wp:gutenverse/text-editor -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-7z09Io","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]}} -->
<div class="section-wrapper" data-id="7z09Io"><section class="wp-block-gutenverse-section guten-element guten-section guten-7z09Io layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-Ol0DVU"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-Ol0DVU"><div class="guten-column-wrapper" data-id="Ol0DVU"><!-- wp:gutenverse/icon-box {"elementId":"guten-7MwyZd","separateButtonLink":false,"title":"Kuta, Bali","titleTag":"h3","description":"Jl. Sunset Road No.815","icon":"gtn gtn-apartment-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"gv-color-white"},"iconBgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"15","left":"0"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"4","right":"0","bottom":"10","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"600"},"parentSelector":".guten-7MwyZd:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-7MwyZd animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="gtn gtn-apartment-light icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Kuta, Bali</h3><p class="icon-box-description">Jl. Sunset Road No.815</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-ry5osU","margin":{"Tablet":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-ry5osU"><div class="guten-column-wrapper" data-id="ry5osU"><!-- wp:gutenverse/icon-box {"elementId":"guten-nQqKlc","separateButtonLink":false,"title":"Denpasar, Bali","titleTag":"h3","description":"Jl. Raya Puputan No 125","icon":"gtn gtn-cityscape-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerPaddingHover":{"Desktop":[]},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"containerBorderHover":{"radius":{"Desktop":[]}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"gv-color-white"},"iconBgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"15","left":"0"}}}},"iconBorderHover":{"radius":{"Desktop":[]}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"10","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"800"},"parentSelector":".guten-nQqKlc:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-nQqKlc animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="gtn gtn-cityscape-light icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Denpasar, Bali</h3><p class="icon-box-description">Jl. Raya Puputan No 125</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-k5uquA","margin":{"Desktop":{"unit":"px","dimension":{"top":"20"}},"Mobile":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="section-wrapper" data-id="k5uquA"><section class="wp-block-gutenverse-section guten-element guten-section guten-k5uquA layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":50},"elementId":"guten-lQPNC0"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-lQPNC0"><div class="guten-column-wrapper" data-id="lQPNC0"><!-- wp:gutenverse/icon-box {"elementId":"guten-HE6K3N","separateButtonLink":false,"title":"Phone Call","titleTag":"h3","description":"(021) 123 - 4567","icon":"gtn gtn-phone1-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"gv-color-white"},"iconBgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"15","left":"0"}}}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"10","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"badgePadding":{"Desktop":[]},"badgeRadius":{"Desktop":[]},"margin":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","bottom":"","right":"","left":""}},"Mobile":[]},"padding":{"Desktop":[],"Tablet":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}},"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1000"},"parentSelector":".guten-HE6K3N:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-HE6K3N animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="gtn gtn-phone1-light icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Phone Call</h3><p class="icon-box-description">(021) 123 - 4567</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":50,"Tablet":null},"elementId":"guten-47yyzn","margin":{"Tablet":{"unit":"px","dimension":{"top":"10"}}},"padding":{"Tablet":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-47yyzn"><div class="guten-column-wrapper" data-id="47yyzn"><!-- wp:gutenverse/icon-box {"elementId":"guten-TTPwcH","separateButtonLink":false,"title":"Send Us A Message","titleTag":"h3","description":"support@example.com","icon":"gtn gtn-email1-light","iconSize":{"Desktop":"30"},"iconPosition":"left","align":{"Desktop":"left"},"containerPadding":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"containerBorder":{"radius":{"Desktop":[]},"all":{"type":"none"}},"iconPadding":{"Desktop":{"unit":"px","dimension":{"top":"20","right":"20","bottom":"20","left":"20"}}},"iconMargin":{"Desktop":{"unit":"px","dimension":{"right":"5"}}},"iconColor":{"type":"variable","id":"gv-color-white"},"iconBgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"15","right":"0","bottom":"15","left":"0"}}}},"titlePadding":{"Desktop":[]},"titleMargin":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"10","left":"0"}}},"titleColor":{"type":"variable","id":"gv-color-text-primary"},"titleTypography":{"type":"variable","id":"gv-font-meta","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"18"},"Mobile":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.4"}},"weight":"500"},"descMargin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"descColor":{"type":"variable","id":"gv-color-text-secondary"},"descTypography":{"type":"variable","id":"gv-font-text","font":{"label":"Heebo","value":"Heebo","type":"google"},"size":{"Desktop":{"unit":"px","point":"16"},"Mobile":{"unit":"px","point":"14"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.7"}},"weight":"300"},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1200"},"parentSelector":".guten-TTPwcH:hover .guten-icon-box-wrapper"} -->
<div class="guten-element guten-TTPwcH animated guten-element-hide desktop-fadeInRight guten-icon-box icon-position-left"><div class="guten-icon-box-wrapper hover-from-left"><div class="icon-box icon-box-header"><div class="icon bg-style-color"><i class="gtn gtn-email1-light icon-style-color"></i></div></div><div class="icon-box icon-box-body"><h3 class="title">Send Us A Message</h3><p class="icon-box-description">support@example.com</p></div></div></div>
<!-- /wp:gutenverse/icon-box --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->

<!-- wp:gutenverse/divider {"elementId":"guten-Xa0Gei","width":{"Desktop":"100"},"dividerColor":{"type":"variable","id":"gv-color-border"},"size":{"Desktop":"1"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"40"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1300"}} -->
<div class="wp-block-gutenverse-divider guten-element guten-divider guten-Xa0Gei animated guten-element-hide desktop-fadeInRight"><div class="guten-divider-wrapper"><div class="guten-divider-default guten-divider-line guten-divider-regular"></div></div></div>
<!-- /wp:gutenverse/divider -->

<!-- wp:gutenverse/section {"isChild":true,"gap":"no","elementId":"guten-liKhTV","verticalAlign":"center","margin":{"Desktop":{"unit":"px","dimension":{"top":"30"}}},"padding":{"Desktop":[]},"animation":{"type":{"Desktop":"fadeInRight"},"duration":"normal","delay":"1400"}} -->
<div class="section-wrapper" data-id="liKhTV"><section class="wp-block-gutenverse-section guten-element guten-section guten-liKhTV animated guten-element-hide desktop-fadeInRight layout-boxed align-stretch"><div class="guten-container guten-column-gap-no"><!-- wp:gutenverse/column {"width":{"Desktop":40.18,"Tablet":30},"sectionVerticalAlign":"center","elementId":"guten-s9xqNo"} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-s9xqNo"><div class="guten-column-wrapper" data-id="s9xqNo"><!-- wp:gutenverse/heading {"elementId":"guten-3lnpuw","type":6,"color":{"type":"variable","id":"gv-color-text-primary"},"typography":{"type":"variable","id":"h6-font","font":{"label":"Helvetica","value":"Helvetica","type":"system"},"size":{"Desktop":{"unit":"px","point":"16"}},"lineHeight":{"Desktop":{"unit":"em","point":"1.3"}},"weight":"400"},"containsAnchorTag":false,"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[]}} -->
<h6 class="wp-block-gutenverse-heading guten-element guten-3lnpuw">Follow Us On Social Media :</h6>
<!-- /wp:gutenverse/heading --></div></div>
<!-- /wp:gutenverse/column -->

<!-- wp:gutenverse/column {"width":{"Desktop":59.81,"Tablet":70,"Mobile":null},"sectionVerticalAlign":"center","elementId":"guten-r6CDT2","margin":{"Desktop":{"unit":"px","dimension":{"top":"","right":"","bottom":"","left":""}}},"padding":{"Desktop":[]}} -->
<div class="wp-block-gutenverse-column guten-element guten-column guten-r6CDT2"><div class="guten-column-wrapper" data-id="r6CDT2"><!-- wp:gutenverse/social-icons {"elementId":"guten-zYpKxB","iconSize":{"Desktop":{"point":"16","unit":"px"}},"gap":{"Desktop":"18"},"alignment":{"Desktop":"flex-start","Mobile":"flex-start"},"color":"custom","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-primary"},"iconBorder":{"radius":{"Desktop":{"unit":"px","dimension":{"top":"5","right":"0","bottom":"5","left":"0"}}}},"itemPadding":{"Desktop":[]},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverBgColor":{"type":"variable","id":"gv-color-text-primary"},"margin":{"Desktop":{"unit":"px","dimension":{"top":"0","right":"","bottom":"","left":"20"}},"Mobile":{"unit":"px","dimension":{"top":"20","right":"0","bottom":"0","left":"0"}}},"padding":{"Desktop":[],"Mobile":[]}} -->
<div class="guten-element guten-social-icons guten-zYpKxB rounded horizontal custom"><!-- wp:gutenverse/social-icon {"elementId":"guten-A1jgck"} -->
<div class="guten-element guten-social-icon guten-A1jgck twitter"><a id="guten-A1jgck" href="#"><i class="fab fa-x-twitter"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-tmLzN3","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-text-primary"},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverBgColor":{"type":"variable","id":"gv-color-primary"}} -->
<div class="guten-element guten-social-icon guten-tmLzN3 facebook"><a id="guten-tmLzN3" href="#"><i class="gtn gtn-facebook-f"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-CW7vra"} -->
<div class="guten-element guten-social-icon guten-CW7vra instagram"><a id="guten-CW7vra" href="#"><i class="gtn gtn-instagram-1-light"></i></a></div>
<!-- /wp:gutenverse/social-icon -->

<!-- wp:gutenverse/social-icon {"elementId":"guten-OQq4te","iconColor":{"type":"variable","id":"gv-color-white"},"bgColor":{"type":"variable","id":"gv-color-text-primary"},"hoverIconColor":{"type":"variable","id":"gv-color-white"},"hoverBgColor":{"type":"variable","id":"gv-color-primary"}} -->
<div class="guten-element guten-social-icon guten-OQq4te youtube"><a id="guten-OQq4te" href="#"><i class="fab fa-youtube"></i></a></div>
<!-- /wp:gutenverse/social-icon --></div>
<!-- /wp:gutenverse/social-icons --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section --></div></div>
<!-- /wp:gutenverse/column --></div></section></div>
<!-- /wp:gutenverse/section -->',
	'images'      => '',
	'pattern_slug' => 'startupzy-companion/startupzy-gutenverse-contact-contact',
	'is_sync' => false,
);
